export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const READ_MESSAGES = 'READ_MESSAGES';

export const CREATE_USER = 'CREATE_USER';
export const READ_USER = 'READ_USER';
export const UPDATE_USER = 'UPDATE_USER';

export const READ_USERLIST = 'READ_USERLIST';

export const MESSAGES_LOADING = 'MESSAGES_LOADING';
